development:
  adapter: postgresql
  encoding: utf8
  database: rails-mister-cocktail_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rails-mister-cocktail_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: rails-mister-cocktail_production
  pool: 5
  username:
  password:
